Switch from Mailable to Notification
spatie/laravel-personal-data-export pull request #50
Opened 2020-11-21 12:02 UTC by ZeProf2Code

2020-11-22 19:27 UTC, freekmurze commented on src/Notifications/PersonalDataExported.php
> +    public $zipFilename;
Use typehints instead of docblocks

2020-11-22 19:28 UTC, freekmurze requested changes
It seems the tests are failing, could you take a look at that?

2020-11-22 19:28 UTC, freekmurze commented on src/Notifications/PersonalDataExported.php
> +     * Create a notification instance.
Remove this and all other docblock, that don't add any meaniful info.

2020-11-29 09:11 UTC, ZeProf2Code commented
It seems the tests are failing because of a bug in L7 prefer-lowest.

2020-11-29 09:23 UTC, freekmurze commented
Feel free to update the lower version to make it work

2020-12-14 06:28 UTC, merged